-- CRIAÇÃO DOS OBJETOS

CREATE OR REPLACE TYPE TP_ENDERECO AS OBJECT(
    cep VARCHAR2(10),
    rua VARCHAR2(100),
    bairro VARCHAR2(100),
    cidade VARCHAR2(100),
    estado CHAR(2)
)NOT FINAL;
/

CREATE OR REPLACE TYPE TP_TELEFONE AS OBJECT(
    numero VARCHAR2(15)
)NOT FINAL;
/

CREATE OR REPLACE TYPE TP_TELEFONES AS VARRAY(5) OF TP_TELEFONE;
/

CREATE OR REPLACE TYPE TP_EMAIL AS OBJECT(
    endereco_email VARCHAR2(50)
)NOT FINAL;
/

CREATE TYPE TP_NT_EMAIL AS TABLE OF TP_EMAIL;
/

CREATE OR REPLACE TYPE TP_PESSOA AS OBJECT(
    id_pessoa INTEGER,
    endereco_pessoa TP_ENDERECO,
    numero_pessoa INTEGER,
    telefones_pessoa TP_TELEFONES,

    MEMBER PROCEDURE infoPessoa(SELF TP_PESSOA)
)NOT FINAL NOT INSTANTIABLE;
/

CREATE OR REPLACE TYPE BODY TP_PESSOA AS
    MEMBER PROCEDURE infoPessoa (SELF TP_PESSOA) IS
        BEGIN
            DBMS_OUTPUT.PUT_LINE('INFORMAÇÕES DA PESSOA');
            DBMS_OUTPUT.PUT_LINE('ID PESSOA: ' || id_pessoa);
            DBMS_OUTPUT.PUT_LINE('ENDERECO: ' || endereco_pessoa);
        END;
END;
/

-- =-=-= Especializações de Pessoa =-=-=
CREATE OR REPLACE TYPE TP_EMPRESA UNDER TP_PESSOA(
    cnpj VARCHAR2(20), 
    razao_social VARCHAR2(50),
    nome_fantasia VARCHAR2(50)
)NOT FINAL;
/

CREATE OR REPLACE TYPE TP_PESSOA_FISICA UNDER TP_PESSOA(
    cpf VARCHAR2(15),
    nome VARCHAR2(100),
    data_de_nascimento DATE,

    OVERRIDING MEMBER PROCEDURE infoPessoa(SELF TP_PESSOA_FISICA)
)NOT FINAL;
/

CREATE OR REPLACE TYPE BODY TP_PESSOA_FISICA AS
    OVERRIDING MEMBER PROCEDURE infoPessoa (SELF TP_PESSOA_FISICA) IS
        BEGIN
            DBMS_OUTPUT.PUT_LINE('INFORMAÇÕES DA PESSOA');
            DBMS_OUTPUT.PUT_LINE('ID PESSOA: ' || id_pessoa);
            DBMS_OUTPUT.PUT_LINE('ENDERECO: ' || endereco_pessoa);
            DBMS_OUTPUT.PUT_LINE('NOME: ' || nome);
            DBMS_OUTPUT.PUT_LINE('CPF: ' || cpf);
            DBMS_OUTPUT.PUT_LINE('DATA DE NASCIMENTO: ' || TO_CHAR(data_de_nascimento));
        END;
END;
/

-- =-=-= Fim Especializações Pessoa =-=-=
CREATE OR REPLACE TYPE TP_SOCIO UNDER TP_PESSOA_FISICA(
    numero_registro INTEGER,
    data_afiliacao DATE,
    valor_investimento NUMBER(10,2), 
    porcentagem_nos_lucros FLOAT(2)
)NOT FINAL;
/

CREATE OR REPLACE TYPE TP_DEPARTAMENTO AS OBJECT(
    numero INTEGER,
    empresa_dep REF TP_EMPRESA, 
    nome VARCHAR2(80),
    data_criacao DATE,
    situacao CHAR(1),

    FINAL MAP MEMBER FUNCTION nomeDepartamento RETURN VARCHAR2

)NOT FINAL;
/

CREATE OR REPLACE TYPE BODY TP_DEPARTAMENTO AS
    FINAL MAP MEMBER FUNCTION nomeDepartamento RETURN VARCHAR2 IS
        d VARCHAR2(80) := nome;
    BEGIN
        RETURN d
    END;
END;
/

CREATE OR REPLACE TYPE TP_CONTRATO AS OBJECT(
    numero_contrato INTEGER,
    tipo_contrato VARCHAR2(80),
    data_admissao DATE, 
    cargo VARCHAR2(50), 
    salario_bruto_mensal NUMBER(10,2),
    jornada_trabalho_semanal INTEGER,

    ORDER MEMBER FUNCTION comparaSalario (f TP_CONTRATO) RETURN INTEGER,

    CONSTRUCTOR FUNCTION TP_CONTRATO(numero_contrato INTEGER, tipo_contrato VARCHAR2, data_admissao DATE, 
        cargo VARCHAR2, salario_bruto_mensal NUMBER, jornada_trabalho_semanal INTEGER)
        RETURN SELF AS RESULT
)NOT FINAL;
/

CREATE OR REPLACE TYPE BODY TP_CONTRATO AS
    CONSTRUCTOR FUNCTION TP_CONTRATO(numero_contrato INTEGER, tipo_contrato VARCHAR2
        data_admissao DATE, cargo VARCHAR2, salario_bruto_mensal NUMBER, jornada_trabalho_semanal INTEGER)
        RETURN SELF AS RESULT AS 
            BEGIN 
                SELF.num_contrato := num_contrato
                SELF.tipo_contrato := tipo_contrato
                SELF.data_admissao := data_admissao
                SELF.cargo := cargo
                SELF.salario_bruto_mensal := salario_bruto_mensal
                SELF.jornada_trabalho_semanal := jornada_trabalho_semanal 
                RETURN;
            END;
    
    ORDER MEMBER FUNCTION comparaSalario(c TP_CONTRATO) RETURN INTEGER IS
    BEGIN
        RETURN SELF.salario_bruto_mensal - c.salario_bruto_mensal;
    END;

END;
/

CREATE OR REPLACE TYPE TP_FUNCIONARIO UNDER TP_PESSOA_FISICA(
    ctps VARCHAR2(15),
    numero_departamento REF TP_DEPARTAMENTO,  
    numero_contrato_func REF TP_CONTRATO, 
    id_empresa_func REF TP_EMPRESA,

    MEMBER FUNCTION salarioBrutoAnual RETURN NUMBER
)NOT FINAL;
/

CREATE OR REPLACE TYPE BODY TP_FUNCIONARIO AS
    MEMBER FUNCTION salarioBrutoAnual RETURN NUMBER IS
    BEGIN
        RETURN numero_contrato_func.salario_bruto_mensal * 12
    END;
END;
/

CREATE OR REPLACE TYPE TP_GERENTE UNDER TP_FUNCIONARIO(
);
/

ALTER TYPE TP_FUNCIONARIO ADD ATTRIBUTE (gerente_func REF TP_GERENTE) CASCADE;

CREATE OR REPLACE TYPE TP_CONTA_BANCARIA AS OBJECT(
    agencia INTEGER, 
    numero_conta INTEGER,
    numero_banco INTEGER, 
    id_titular REF TP_PESSOA 
)NOT FINAL;
/

CREATE OR REPLACE TYPE TP_VANTAGEM AS OBJECT(
    codigo INTEGER, 
    descricao VARCHAR2(50),
    valor NUMBER(10,2) 
)NOT FINAL;
/

CREATE OR REPLACE TYPE TP_DESCONTO AS OBJECT(
    codigo INTEGER, 
    descricao VARCHAR2(50),
    valor NUMBER(10,2) 
)NOT FINAL;
/

CREATE OR REPLACE TYPE TP_PONTO AS OBJECT(
    protocolo INTEGER,
    data_atual DATE, 
    ponto_funcionario REF TP_FUNCIONARIO 
)NOT FINAL;
/

CREATE OR REPLACE TYPE TP_ENTRADA AS OBJECT(
    hora_entrada VARCHAR2(12), 
    protocolo_ponto REF TP_PONTO 
)NOT FINAL;
/

CREATE OR REPLACE TYPE TP_SAIDA AS OBJECT(
    hora_saida VARCHAR2(12), 
    protocolo_ponto REF TP_PONTO 
)NOT FINAL;
/

CREATE OR REPLACE TYPE TP_PARTICIPACAO AS OBJECT(
    part_socio REF TP_SOCIO, 
    part_empresa REF TP_EMPRESA 
)NOT FINAL;
/

CREATE OR REPLACE TYPE TP_BONUS AS OBJECT(
    identificador INTEGER, 
    porcentagem_bonus FLOAT(2), 
    socio_bonus REF TP_SOCIO,
    empresa_bonus REF TP_EMPRESA
)NOT FINAL;
/

CREATE OR REPLACE TYPE TP_ACRESCIMO AS OBJECT(
    codigo_vantagem REF TP_VANTAGEM, 
    num_contrato REF TP_CONTRATO
)NOT FINAL;
/

CREATE OR REPLACE TYPE TP_APLICACAO AS OBJECT(
    codigo_desconto REF TP_DESCONTO, 
    num_contrato REF TP_CONTRATO
)NOT FINAL;
/

CREATE OR REPLACE TYPE TP_PAGAMENTO AS OBJECT(
    pag_empresa REF TP_EMPRESA, 
    pag_funcionario REF TP_FUNCIONARIO,
    pag_data DATE
)NOT FINAL;
/
-- FIM CRIAÇÃO OBJETOS

-- TABELAS
CREATE TABLE TB_EMPRESA OF TP_EMPRESA(
    cnpj UNIQUE,
    id_pessoa PRIMARY KEY 
);
/

CREATE TABLE TB_SOCIO OF TP_SOCIO(
    id_pessoa PRIMARY KEY 
);
/

CREATE TABLE TB_DEPARTAMENTO OF TP_DEPARTAMENTO(
    numero PRIMARY KEY,
    empresa_dep WITH ROWID REFERENCES TB_EMPRESA
);
/

CREATE TABLE TB_CONTRATO OF TP_CONTRATO(
    numero_contrato PRIMARY KEY,

    CHECK(salario_bruto_mensal >= 1100),
    CHECK(jornada_trabalho_semanal <= 44)
);
/

CREATE TABLE TB_FUNCIONARIO OF TP_FUNCIONARIO(
    id_pessoa PRIMARY KEY,
    ctps UNIQUE,
    numero_departamento SCOPE IS TB_DEPARTAMENTO,
    numero_contrato_func SCOPE IS TB_CONTRATO,
    id_empresa_func SCOPE IS TB_EMPRESA
);
/

CREATE TABLE TB_CONTA_BANCARIA OF TP_CONTA_BANCARIA(
    numero_conta PRIMARY KEY
);
/

CREATE TABLE TB_VANTAGEM OF TP_VANTAGEM(
    codigo PRIMARY KEY
);
/

CREATE TABLE TB_DESCONTO OF TP_DESCONTO(
    codigo PRIMARY KEY
);
/

CREATE TABLE TB_PONTO OF TP_PONTO(
    protocolo PRIMARY KEY, 
    ponto_funcionario SCOPE IS TB_FUNCIONARIO 
);
/

CREATE TABLE TB_ENTRADA OF TP_ENTRADA(
    protocolo_ponto SCOPE IS TB_PONTO
);
/

CREATE TABLE TB_SAIDA OF TP_SAIDA(
    protocolo_ponto SCOPE IS TB_PONTO
);
/

CREATE TABLE TB_PARTICIPACAO OF TP_PARTICIPACAO(
    part_socio SCOPE IS TB_SOCIO,
    part_empresa SCOPE IS TB_EMPRESA
);
/

CREATE TABLE TB_BONUS OF TP_BONUS(
    identificador PRIMARY KEY,
    socio_bonus SCOPE IS TB_SOCIO,
    empresa_bonus SCOPE IS TB_EMPRESA
);
/

CREATE TABLE TB_ACRESCIMO OF TP_ACRESCIMO(
    codigo_vantagem SCOPE IS TB_VANTAGEM,
    num_contrato SCOPE IS TB_CONTRATO
);
/

CREATE TABLE TB_APLICACAO OF TP_APLICACAO(
    codigo_desconto SCOPE IS TB_DESCONTO,
    num_contrato SCOPE IS TB_CONTRATO
);
/

CREATE TABLE TB_PAGAMENTO OF TP_PAGAMENTO(
    pag_empresa SCOPE IS TB_EMPRESA,
    pag_funcionario SCOPE IS TB_FUNCIONARIO
);
/

-- NESTED TABLE
CREATE TABLE TB_EMAILS_FUNCIONARIOS(
    id_pessoa_email INTEGER,
    lista_emails TP_NT_EMAIL
)
NESTED TABLE lista_emails STORE AS TB_LISTA_EMAIL;
/

-- INSERTS
-- EMPRESA
INSERT INTO TB_EMPRESA VALUES (1, TP_ENDERECO('12345678', 'Rua 1', 'Bairro 1', 'Recife', 'PE'), 400, 
    TP_TELEFONES(TP_TELEFONE(81934648400), TP_TELEFONE(81998763432)), '14233567000123', 'APPLE COMPUTER INC.', 'APPLE');

INSERT INTO TB_EMPRESA VALUES (2, TP_ENDERECO('12345679', 'Rua 2', 'Bairro 2', 'Rio de Janeiro', 'RJ'), 401, 
    TP_TELEFONES(TP_TELEFONE(32934648410)), '14233567011234', 'SAMSUNG ELECTRONICS LTD.', 'SAMSUNG');

INSERT INTO TB_EMPRESA VALUES (3, TP_ENDERECO('12345670', 'Rua 3', 'Bairro 3', 'Lagoa', 'RJ'), 402, 
    TP_TELEFONES(TP_TELEFONE(66998763423), TP_TELEFONE(21934648421), TP_TELEFONE(19998763422)), '51533567000124', 'WALMART INC.', 'WALMART');

INSERT INTO TB_EMPRESA VALUES (4, TP_ENDERECO('12345671', 'Rua 4', 'Bairro 4', 'São Paulo', 'SP'), 403, 
    TP_TELEFONES(TP_TELEFONE(13934648423)), '55233567000125', 'GENERAL MOTORS CORPORATION', 'GM');

INSERT INTO TB_EMPRESA VALUES (5, TP_ENDERECO('12345672', 'Rua 5', 'Bairro 5', 'Belo Horizonte', 'MG'), 404, 
    TP_TELEFONES(TP_TELEFONE(11998763424), TP_TELEFONE(11934648425)), '12233567000126', 'PETRÓLEO BRASILEIRO S.A.', 'PETROBRAS');

INSERT INTO TB_EMPRESA VALUES (6, TP_ENDERECO('12345675', 'Rua 6', 'Bairro 6', 'Santa Maria', 'DF'), 405, 
    TP_TELEFONES(TP_TELEFONE(87998763433)), '94545267110241', 'ROYAL DUTCH SHELL', 'SHELL');

INSERT INTO TB_EMPRESA VALUES (7, TP_ENDERECO('23456789', 'Rua 7', 'Bairro 7', 'Salvador', 'BA'), 406, 
    TP_TELEFONES(TP_TELEFONE(86994763433)), '33117875486512', 'RED BULL GMBH', 'RED BULL');

INSERT INTO TB_EMPRESA VALUES (8, TP_ENDERECO('23456780', 'Rua 8', 'Bairro 8', 'Porto Alegre', 'RS'), 407, 
    TP_TELEFONES(TP_TELEFONE(86997783433), TP_TELEFONE(84934648425)), '45214887454521', 'IBAC LTDA', 'CACAU SHOW');

INSERT INTO TB_EMPRESA VALUES (9, TP_ENDERECO('23456781', 'Rua 9', 'Bairro 9', 'Belém', 'PA'), 408, 
    TP_TELEFONES(TP_TELEFONE(84998761234)), '64878455411549', 'DISNEY ENTERPRISES INC.', 'DISNEY');

INSERT INTO TB_EMPRESA VALUES (10, TP_ENDERECO('23456782', 'Rua A', 'Bairro A', 'Goiânia', 'GO'), 409, 
    TP_TELEFONES(TP_TELEFONE(83994761235), TP_TELEFONE(82997782347)), '24184512514650', 'AMAZON.COM INC.', 'AMAZON');

-- SÓCIO
INSERT INTO TB_SOCIO VALUES (11, TP_ENDERECO('23456783', 'Rua B', 'Bairro B', 'Maceió', 'AL'), 14, 
    TP_TELEFONES(TP_TELEFONE(94904761231)), 
        '11111111111', 'ANA BEATRIZ GOMES', '04-FEB-1981', 2, '11-DEC-2020', 258967.14, 0.15);

INSERT INTO TB_SOCIO VALUES (12, TP_ENDERECO('23456784', 'Rua C', 'Bairro C', 'Juazeiro do Norte', 'CE'), 14, 
    TP_TELEFONES(TP_TELEFONE(95904764781)), 
        '22222222222', 'GERALDO FRANSCICO DA SILVA', '05-MAR-1982', 4, '05-MAR-1982', 57601.66, 0.01);

INSERT INTO TB_SOCIO VALUES (13, TP_ENDERECO('34567890', 'Rua D', 'Bairro D', 'Sumaré', 'SP'), 14, 
    TP_TELEFONES(TP_TELEFONE(31904761231)), 
        '33333333333', 'MARIANA SOARES DE LIMA', '06-APR-1983', 6, '21-JAN-2021', 14967.14, 0.03);

INSERT INTO TB_SOCIO VALUES (14, TP_ENDERECO('34567891', 'Rua E', 'Bairro E', 'Barueri', 'SP'), 14, 
    TP_TELEFONES(TP_TELEFONE(11904711233)), 
        '44444444444', 'LUIZ MELO DE SOUZA', '07-MAY-1984', 3, '15-APR-2017', 10000000, 0.2);

INSERT INTO TB_SOCIO VALUES (15, TP_ENDERECO('34567892', 'Rua F', 'Bairro F', 'Imperatriz', 'MA'), 14, 
    TP_TELEFONES(TP_TELEFONE(86904461249)), 
       '55555555555', 'MARIA LUIZA FERREIRA', '08-OCT-1984', 5, '11-DEC-2020', 487414.12, 0.08);

INSERT INTO TB_SOCIO VALUES (16, TP_ENDERECO('34567893', 'Rua G', 'Bairro G', 'Cabo de Santo Agostinho', 'PE'), 14, 
    TP_TELEFONES(TP_TELEFONE(88904761231)), 
        '66666666666', 'VINÍCIUS DE MORAES', '09-DEC-2001', 7, '26-SEP-2019', 3194047.10, 0.1);

-- DEPARTAMENTO
INSERT INTO TB_DEPARTAMENTO VALUES(1, (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 1), 'FINANÇAS', '07-FEB-2014', 'A');
INSERT INTO TB_DEPARTAMENTO VALUES(2, (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 1), 'MARKETING', '02-FEB-2016', 'A');
-- EMPRESA 2
INSERT INTO TB_DEPARTAMENTO VALUES(3, (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 2), 'FINANÇAS', '05-MAY-2013', 'A');
INSERT INTO TB_DEPARTAMENTO VALUES(4, (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 2), 'MARKETING', '11-APR-2013', 'A');
-- EMPRESA 3
INSERT INTO TB_DEPARTAMENTO VALUES(5, (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 3), 'DESENVOLVIMENTO E PESQUISA', '04-NOV-2011', 'A');
INSERT INTO TB_DEPARTAMENTO VALUES(6, (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 3), 'MARKETING', '03-DEC-2011', 'A');
-- EMPRESA 4
INSERT INTO TB_DEPARTAMENTO VALUES(7, (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 4), 'CONTROLE DE QUALIDADE', '14-NOV-1999', 'A');
INSERT INTO TB_DEPARTAMENTO VALUES(8, (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 4), 'DESENVOLVIMENTO E PESQUISA', '13-MAY-2000', 'A');
-- EMPRESA 5
INSERT INTO TB_DEPARTAMENTO VALUES(9,  (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 5), 'TECNOLOGIA', '14-SEP-2008', 'A');
INSERT INTO TB_DEPARTAMENTO VALUES(10, (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 5), 'COMERCIAL', '03-DEC-2008', 'A');
-- EMPRESA 6 
INSERT INTO TB_DEPARTAMENTO VALUES(11, (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 6), 'CONTROLE E QUALIDADE', '07-FEB-2001', 'A');
INSERT INTO TB_DEPARTAMENTO VALUES(12, (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 6), 'MARKETING', '27-MAY-2002', 'I');
-- EMPRESA 7
INSERT INTO TB_DEPARTAMENTO VALUES(13, (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 7), 'COMERCIAL', '09-JUN-2004', 'A');
INSERT INTO TB_DEPARTAMENTO VALUES(14, (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 7), 'FINANÇAS', '03-JULY-2004', 'A');
-- EMPRESA 8
INSERT INTO TB_DEPARTAMENTO VALUES(15, (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 8), 'CONTROLE DE QUALIDADE', '16-APR-2005', 'A');
INSERT INTO TB_DEPARTAMENTO VALUES(16, (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 8), 'PESQUISA E DESENVOLVIMENTO', '03-MAY-2005', 'I');
-- EMPRESA 9
INSERT INTO TB_DEPARTAMENTO VALUES(17, (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 9), 'COMUNICAÇÃO', '02-JAN-1984', 'A');
INSERT INTO TB_DEPARTAMENTO VALUES(18, (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 9), 'FINANÇAS', '03-SEP-1984', 'I');
-- EMPRESA 10
INSERT INTO TB_DEPARTAMENTO VALUES(19, (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 10), 'COMUNICAÇÃO', '14-NOV-2001', 'A');
INSERT INTO TB_DEPARTAMENTO VALUES(20, (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 10), 'COMERCIAL', '13-DEC-2011', 'A');

-- CONTRATO
INSERT INTO TB_CONTRATO VALUES (1, 'CLT', '12-DEC-2012', 'CLT 1', 1736.26, 44);
INSERT INTO TB_CONTRATO VALUES (2, 'CLT', '10-DEC-2013', 'CLT 2', 2336.62, 44);
INSERT INTO TB_CONTRATO VALUES (3, 'PJ', '05-MAY-2021', 'PJ 1', 6047.66, 30);
INSERT INTO TB_CONTRATO VALUES (4, 'ESTÁGIO', '11-APR-2020', 'ESTAGIÁRIO 1', 1200, 20);
INSERT INTO TB_CONTRATO VALUES (5, 'CLT', '24-JUN-2018', 'CLT 3', 2744, 44);
INSERT INTO TB_CONTRATO VALUES (6, 'CLT', '10-DEC-2013', 'CLT 2', 1336.62, 44);
INSERT INTO TB_CONTRATO VALUES (7, 'TERCEIRIZADO', '25-JULY-2021', 'TC 1', 1200.80, 36);
INSERT INTO TB_CONTRATO VALUES (8, 'ESTÁGIO', '27-APR-2021', 'ESTAGIÁRIO 2', 2000, 20);
INSERT INTO TB_CONTRATO VALUES (9, 'CLT', '04-JULY-2019', 'CLT 3', 25000, 44);
INSERT INTO TB_CONTRATO VALUES (10, 'CLT', '14-DEC-2014', 'CLT 2', 7548.14, 44);
INSERT INTO TB_CONTRATO VALUES (11, 'CLT', '20-JULY-2015', 'CLT 1', 2136.80, 44);
INSERT INTO TB_CONTRATO VALUES (12, 'PJ', '17-JUN-2020', 'PJ 2', 4284.97, 40);
INSERT INTO TB_CONTRATO VALUES (13, 'CLT', '22-JUN-2021', 'CLT 1', 1736.26, 44);
INSERT INTO TB_CONTRATO VALUES (14, 'CLT', '20-AUG-2013', 'CLT 2', 2336.62, 44);
INSERT INTO TB_CONTRATO VALUES (15, 'PJ', '05-AUG-2021', 'PJ 1', 6047.66, 30);
INSERT INTO TB_CONTRATO VALUES (16, 'ESTÁGIO', '10-APR-2020', 'ESTAGIÁRIO 1', 1200, 20);
INSERT INTO TB_CONTRATO VALUES (17, 'CLT', '14-JULY-2018', 'CLT 3', 2744, 44);
INSERT INTO TB_CONTRATO VALUES (18, 'CLT', '20-SEP-2019', 'CLT 2', 2336.62, 44);
INSERT INTO TB_CONTRATO VALUES (19, 'TERCEIRIZADO', '25-OCT-2021', 'TC 1', 2200.80, 36);
INSERT INTO TB_CONTRATO VALUES (20, 'ESTÁGIO', '27-APR-2021', 'ESTAGIÁRIO 2', 1800, 20);
INSERT INTO TB_CONTRATO VALUES (21, 'CLT', '28-FEB-2019', 'CLT 3', 5000, 44);
INSERT INTO TB_CONTRATO VALUES (22, 'CLT', '12-DEC-2018', 'CLT 2', 7002.14, 44);
INSERT INTO TB_CONTRATO VALUES (23, 'CLT', '20-JULY-2015', 'CLT 1', 2136.80, 44);
INSERT INTO TB_CONTRATO VALUES (24, 'PJ', '17-JUN-2020', 'PJ 2', 4284.97, 40);

-- FUNCIONARIO
INSERT INTO TB_FUNCIONARIO VALUES (17, 
    TP_ENDERECO('34567894', 'Rua H', 'Bairro H', 'Angra dos Reis', 'RJ'), 4, 
        TP_TELEFONES(TP_TELEFONE(43244648423)), 
            '77777777777', 'WILLIAN SHAKESPEARE', '14-FEB-1989', '12345', 
                (SELECT REF(D) FROM TB_DEPARTAMENTO D WHERE numero = 1),
                    (SELECT REF(C) FROM TB_CONTRATO C WHERE numero_contrato = 1),
                        (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 1), NULL);

INSERT INTO TB_FUNCIONARIO VALUES (18, 
    TP_ENDERECO('34567895', 'Rua I', 'Bairro I', 'Lages', 'SC'), 147, 
        TP_TELEFONES(TP_TELEFONE(42338763424)), 
           '88888888888', 'RENÉ DESCARTES', '25-MAR-1994', '12346',
                (SELECT REF(D) FROM TB_DEPARTAMENTO D WHERE numero = 1),
                    (SELECT REF(C) FROM TB_CONTRATO C WHERE numero_contrato = 2),
                        (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 1), NULL);

INSERT INTO TB_FUNCIONARIO VALUES (19, 
    TP_ENDERECO('45678910', 'Rua J', 'Bairro J', 'Camaragibe', 'PE'), 250, 
        TP_TELEFONES(TP_TELEFONE(54324648425)), 
            99999999999, 'MAO TSÉ-TUNG', '16-APR-1976', '12347',
                (SELECT REF(D) FROM TB_DEPARTAMENTO D WHERE numero = 2),
                    (SELECT REF(C) FROM TB_CONTRATO C WHERE numero_contrato = 3),
                        (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 2), NULL);

INSERT INTO TB_FUNCIONARIO VALUES (20, 
    TP_ENDERECO('23456783', 'Rua B', 'Bairro B', 'Maceió', 'AL'), 44, 
        TP_TELEFONES(TP_TELEFONE(54338763433)), 
            12121212122, 'CARLOS MAGNO', '17-DEC-1999', '12348',
                (SELECT REF(D) FROM TB_DEPARTAMENTO D WHERE numero = 2),
                    (SELECT REF(C) FROM TB_CONTRATO C WHERE numero_contrato = 4),
                        (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 2), NULL);

INSERT INTO TB_FUNCIONARIO VALUES (21, 
    TP_ENDERECO('45678911', 'Rua K', 'Bairro K', 'Sonhos', 'AM'), 62, 
        TP_TELEFONES(TP_TELEFONE(54344763433)), 
            13131313133, 'FRANCISCO BUARQUE DE HOLLANDA', '24-MAR-1991', '12349',
                (SELECT REF(D) FROM TB_DEPARTAMENTO D WHERE numero = 3),
                    (SELECT REF(C) FROM TB_CONTRATO C WHERE numero_contrato = 5),
                        (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 3), NULL);

INSERT INTO TB_FUNCIONARIO VALUES (22, 
    TP_ENDERECO('45678912', 'Rua L', 'Bairro L', 'Pesadelos', 'PR'), 23, 
        TP_TELEFONES(TP_TELEFONE(54357783433)), 
            14141414141, 'REYNALDO CISOTTO JÚNIOR', '11-MAY-1972', '12340',
                (SELECT REF(D) FROM TB_DEPARTAMENTO D WHERE numero = 3),
                    (SELECT REF(C) FROM TB_CONTRATO C WHERE numero_contrato = 6),
                        (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 3), NULL);

INSERT INTO TB_FUNCIONARIO VALUES (23, 
    TP_ENDERECO('45678913', 'Rua M', 'Bairro M', 'Tears', 'DF'), 99, 
        TP_TELEFONES(TP_TELEFONE(54364648425)), 
            21212121214, 'PAULO REGLUS NEVES FREIRE', '22-JUN-1989', '12341',
                (SELECT REF(D) FROM TB_DEPARTAMENTO D WHERE numero = 4),
                    (SELECT REF(C) FROM TB_CONTRATO C WHERE numero_contrato = 7),
                        (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 4), NULL);

INSERT INTO TB_FUNCIONARIO VALUES (24, 
    TP_ENDERECO('45678914', 'Rua N', 'Bairro N', 'Love', 'MS'), 297, 
        TP_TELEFONES(TP_TELEFONE(54378761234)), 
            44444474100, 'CARLOS DRUMMOND DE ANDRADE', '14-JULY-2002', '12342',
                (SELECT REF(D) FROM TB_DEPARTAMENTO D WHERE numero = 4),
                    (SELECT REF(C) FROM TB_CONTRATO C WHERE numero_contrato = 8),
                        (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 4), NULL);

INSERT INTO TB_FUNCIONARIO VALUES (25, 
    TP_ENDERECO('45678915', 'Rua O', 'Bairro O', 'Nossa Senhora do Socorro', 'SE'), 605, 
        TP_TELEFONES(TP_TELEFONE(54384761235)), 
            98412574101, 'MARIA LUIZA DA SILVA', '18-OCT-1974', '12343',
                (SELECT REF(D) FROM TB_DEPARTAMENTO D WHERE numero = 5),
                    (SELECT REF(C) FROM TB_CONTRATO C WHERE numero_contrato = 9),
                        (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 5), NULL);

INSERT INTO TB_FUNCIONARIO VALUES (26, 
    TP_ENDERECO('12345678', 'Rua 1', 'Bairro 1', 'Recife', 'PE'), 302, 
        TP_TELEFONES(TP_TELEFONE(54397782347)), 
            64555712560, 'VINÍCIUS PEREIRA DE ANDRADE', '19-JAN-1991', '12344',
                (SELECT REF(D) FROM TB_DEPARTAMENTO D WHERE numero = 5),
                    (SELECT REF(C) FROM TB_CONTRATO C WHERE numero_contrato = 10),
                        (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 5), NULL);

INSERT INTO TB_FUNCIONARIO VALUES (27, 
    TP_ENDERECO('12345679', 'Rua 2', 'Bairro 2', 'Rio de Janeiro', 'RJ'), 203, 
        TP_TELEFONES(TP_TELEFONE(43294654321)), 
            14896147807, 'ALVARO MAMUTE CAMARGO', '09-SEP-1981', '22340',
                (SELECT REF(D) FROM TB_DEPARTAMENTO D WHERE numero = 6),
                    (SELECT REF(C) FROM TB_CONTRATO C WHERE numero_contrato = 11),
                        (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 6), NULL);

INSERT INTO TB_FUNCIONARIO VALUES (28, 
    TP_ENDERECO('12345670', 'Rua 3', 'Bairro 3', 'Lagoa', 'RJ'), 505, 
        TP_TELEFONES(TP_TELEFONE(43288754320)), 
            75416475214, 'AYRTON SENNA DA SILVA', '15-NOV-1960', '22341',
                (SELECT REF(D) FROM TB_DEPARTAMENTO D WHERE numero = 6),
                    (SELECT REF(C) FROM TB_CONTRATO C WHERE numero_contrato = 12),
                        (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 6), NULL);

INSERT INTO TB_FUNCIONARIO VALUES (29, 
    TP_ENDERECO('12345671', 'Rua 4', 'Bairro 4', 'São Paulo', 'SP'), 200, 
        TP_TELEFONES(TP_TELEFONE(43274604321)), 
            55425542157, 'ALBERTO SANTOS DUMONT', '06-AUG-1973', '22342',
                (SELECT REF(D) FROM TB_DEPARTAMENTO D WHERE numero = 7),
                    (SELECT REF(C) FROM TB_CONTRATO C WHERE numero_contrato = 13),
                        (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 7), NULL);

INSERT INTO TB_FUNCIONARIO VALUES (30, 
    TP_ENDERECO('12345672', 'Rua 5', 'Bairro 5', 'Belo Horizonte', 'MG'), 7011, 
        TP_TELEFONES(TP_TELEFONE(43268704322)), 
            97423645179, 'JULIANNA CRISTINA DE SOUSA', '27-AUG-1994', '22343',
                (SELECT REF(D) FROM TB_DEPARTAMENTO D WHERE numero = 7),
                    (SELECT REF(C) FROM TB_CONTRATO C WHERE numero_contrato = 14),
                        (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 7), NULL);

INSERT INTO TB_FUNCIONARIO VALUES (31, 
    TP_ENDERECO('12345675', 'Rua 6', 'Bairro 6', 'Santa Maria', 'DF'), 678, 
        TP_TELEFONES(TP_TELEFONE(43244604323)), 
            94512479644, 'EDUARDA FERREIRA CARDOSO', '27-FEB-1998', '22344',
                (SELECT REF(D) FROM TB_DEPARTAMENTO D WHERE numero = 8),
                    (SELECT REF(C) FROM TB_CONTRATO C WHERE numero_contrato = 15),
                        (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 8), NULL);

INSERT INTO TB_FUNCIONARIO VALUES (32, 
    TP_ENDERECO('23456789', 'Rua 7', 'Bairro 7', 'Salvador', 'BA'), 441, 
        TP_TELEFONES(TP_TELEFONE(42338704324)), 
            46415541046, 'AMANDA BAPTISTA NEVES', '05-MAR-1986', '22345', 
                (SELECT REF(D) FROM TB_DEPARTAMENTO D WHERE numero = 8),
                    (SELECT REF(C) FROM TB_CONTRATO C WHERE numero_contrato = 16),
                        (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 8), NULL);

INSERT INTO TB_FUNCIONARIO VALUES (33, 
    TP_ENDERECO('23456780', 'Rua 8', 'Bairro 8', 'Porto Alegre', 'RS'), 19, 
        TP_TELEFONES(TP_TELEFONE(67324604325)), 
            48789621874, 'MÁRIO SANTIAGO JUNIOR', '06-APR-1983', '22346',
                (SELECT REF(D) FROM TB_DEPARTAMENTO D WHERE numero = 9),
                    (SELECT REF(C) FROM TB_CONTRATO C WHERE numero_contrato = 17),
                        (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 9), NULL);

INSERT INTO TB_FUNCIONARIO VALUES (34, 
    TP_ENDERECO('23456781', 'Rua 9', 'Bairro 9', 'Belém', 'PA'), 7, 
        TP_TELEFONES(TP_TELEFONE(68338704326)), 
            14567445213, 'RENATA MENDES SILVA', '14-JUN-1977', '22347',
                (SELECT REF(D) FROM TB_DEPARTAMENTO D WHERE numero = 9),
                    (SELECT REF(C) FROM TB_CONTRATO C WHERE numero_contrato = 18),
                        (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 9), NULL);

INSERT INTO TB_FUNCIONARIO VALUES (35, 
    TP_ENDERECO('23456782', 'Rua A', 'Bairro A', 'Goiânia', 'GO'), 1, 
        TP_TELEFONES(TP_TELEFONE(69344704327)), 
            31465741147, 'JOSÉ ALENCAR GOMES DA SILVA', '18-JULY-2000', '22348',
                (SELECT REF(D) FROM TB_DEPARTAMENTO D WHERE numero = 10),
                    (SELECT REF(C) FROM TB_CONTRATO C WHERE numero_contrato = 19),
                        (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 10), NULL);

INSERT INTO TB_FUNCIONARIO VALUES (36, 
    TP_ENDERECO('23456782', 'Rua A', 'Bairro A', 'Goiânia', 'GO'), 2, 
        TP_TELEFONES(TP_TELEFONE(88357704328)), 
            01487454665, 'JÚLIA SANTANA GALVÃO', '29-SEP-2001', '22349',
                (SELECT REF(D) FROM TB_DEPARTAMENTO D WHERE numero = 10),
                    (SELECT REF(C) FROM TB_CONTRATO C WHERE numero_contrato = 20),
                        (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 10), NULL);

INSERT INTO TB_FUNCIONARIO VALUES (37, 
    TP_ENDERECO('34567893', 'Rua G', 'Bairro G', 'Cabo de Santo Agostinho', 'PE'), 33, 
        TP_TELEFONES(TP_TELEFONE(74364604329)), 
            45416575543, 'ANA BEATRIZ DE SOUZA', '01-JAN-1996', '32340',
                (SELECT REF(D) FROM TB_DEPARTAMENTO D WHERE numero = 1),
                    (SELECT REF(C) FROM TB_CONTRATO C WHERE numero_contrato = 21),
                        (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 1), NULL);

INSERT INTO TB_FUNCIONARIO VALUES (38, 
    TP_ENDERECO('34567895', 'Rua I', 'Bairro I', 'Lages', 'SC'), 41, 
        TP_TELEFONES(TP_TELEFONE(71378704330)), 
            24764731218, 'DERCY GONÇALVES COSTA', '25-NOV-2001', '32341',
                (SELECT REF(D) FROM TB_DEPARTAMENTO D WHERE numero = 2),
                    (SELECT REF(C) FROM TB_CONTRATO C WHERE numero_contrato = 22),
                        (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 2), NULL);

INSERT INTO TB_FUNCIONARIO VALUES (39, 
    TP_ENDERECO('45678910', 'Rua J', 'Bairro J', 'Camaragibe', 'PE'), 10, 
        TP_TELEFONES(TP_TELEFONE(99384704331)), 
            88452421466, 'MARINA ALVES CRUZ', '16-AUG-1991', '32342',
                (SELECT REF(D) FROM TB_DEPARTAMENTO D WHERE numero = 5),
                    (SELECT REF(C) FROM TB_CONTRATO C WHERE numero_contrato = 23),
                        (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 3), NULL);

INSERT INTO TB_FUNCIONARIO VALUES (40, 
    TP_ENDERECO('45678912', 'Rua L', 'Bairro L', 'Pesadelos', 'PR'), 12, 
        TP_TELEFONES(TP_TELEFONE(97397704332)), 
            45411213447, 'MARIA CAROLINA DA SILVA', '21-FEB-1987', '32343',
                (SELECT REF(D) FROM TB_DEPARTAMENTO D WHERE numero = 8),
                    (SELECT REF(C) FROM TB_CONTRATO C WHERE numero_contrato = 24),
                        (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 7), NULL);

-- CONTA BANCARIA
INSERT INTO TB_CONTA_BANCARIA VALUES(1, 1230, 10, (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 1));
INSERT INTO TB_CONTA_BANCARIA VALUES(2, 1231, 10, (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 2));
INSERT INTO TB_CONTA_BANCARIA VALUES(3, 1232, 11, (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 3));
INSERT INTO TB_CONTA_BANCARIA VALUES(4, 1233, 12, (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 4));
INSERT INTO TB_CONTA_BANCARIA VALUES(5, 1234, 14, (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 5));
INSERT INTO TB_CONTA_BANCARIA VALUES(5, 1235, 15, (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 6));
INSERT INTO TB_CONTA_BANCARIA VALUES(5, 1226, 15, (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 7));
INSERT INTO TB_CONTA_BANCARIA VALUES(4, 1227, 15, (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 8));
INSERT INTO TB_CONTA_BANCARIA VALUES(6, 1228, 18, (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 9));
INSERT INTO TB_CONTA_BANCARIA VALUES(9, 1229, 18, (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 10));
INSERT INTO TB_CONTA_BANCARIA VALUES(1, 2230, 10, (SELECT REF(S) FROM TB_SOCIO S WHERE id_pessoa = 11));
INSERT INTO TB_CONTA_BANCARIA VALUES(2, 2231, 10, (SELECT REF(S) FROM TB_SOCIO S WHERE id_pessoa = 12));
INSERT INTO TB_CONTA_BANCARIA VALUES(3, 2232, 11, (SELECT REF(S) FROM TB_SOCIO S WHERE id_pessoa = 13));
INSERT INTO TB_CONTA_BANCARIA VALUES(4, 2233, 12, (SELECT REF(S) FROM TB_SOCIO S WHERE id_pessoa = 14));
INSERT INTO TB_CONTA_BANCARIA VALUES(5, 2234, 14, (SELECT REF(S) FROM TB_SOCIO S WHERE id_pessoa = 15));
INSERT INTO TB_CONTA_BANCARIA VALUES(5, 2235, 15, (SELECT REF(S) FROM TB_SOCIO S WHERE id_pessoa = 16));
INSERT INTO TB_CONTA_BANCARIA VALUES(5, 2226, 15, (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 17));
INSERT INTO TB_CONTA_BANCARIA VALUES(4, 2227, 15, (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 18));
INSERT INTO TB_CONTA_BANCARIA VALUES(6, 2228, 18, (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 19));
INSERT INTO TB_CONTA_BANCARIA VALUES(9, 2229, 18, (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 20));
INSERT INTO TB_CONTA_BANCARIA VALUES(1, 3230, 10, (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 21));
INSERT INTO TB_CONTA_BANCARIA VALUES(2, 3231, 10, (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 22));
INSERT INTO TB_CONTA_BANCARIA VALUES(3, 3232, 11, (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 23));
INSERT INTO TB_CONTA_BANCARIA VALUES(4, 3233, 12, (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 24));
INSERT INTO TB_CONTA_BANCARIA VALUES(5, 3234, 14, (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 25));
INSERT INTO TB_CONTA_BANCARIA VALUES(5, 3235, 15, (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 26));
INSERT INTO TB_CONTA_BANCARIA VALUES(5, 3226, 15, (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 27));
INSERT INTO TB_CONTA_BANCARIA VALUES(4, 3227, 15, (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 28));
INSERT INTO TB_CONTA_BANCARIA VALUES(6, 3228, 18, (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 29));
INSERT INTO TB_CONTA_BANCARIA VALUES(9, 3229, 18, (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 30));
INSERT INTO TB_CONTA_BANCARIA VALUES(1, 4230, 10, (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 31));
INSERT INTO TB_CONTA_BANCARIA VALUES(2, 4231, 10, (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 32));
INSERT INTO TB_CONTA_BANCARIA VALUES(3, 4232, 11, (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 33));
INSERT INTO TB_CONTA_BANCARIA VALUES(4, 4233, 12, (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 34));
INSERT INTO TB_CONTA_BANCARIA VALUES(5, 4234, 14, (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 35));
INSERT INTO TB_CONTA_BANCARIA VALUES(5, 4235, 15, (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 36));
INSERT INTO TB_CONTA_BANCARIA VALUES(5, 4226, 15, (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 37));
INSERT INTO TB_CONTA_BANCARIA VALUES(4, 4227, 15, (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 38));
INSERT INTO TB_CONTA_BANCARIA VALUES(6, 4228, 18, (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 39));
INSERT INTO TB_CONTA_BANCARIA VALUES(9, 4229, 18, (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 40));

-- VANTAGEM
INSERT INTO TB_VANTAGEM VALUES(1, 'FÉRIAS REMUNERADAS', 1000);
INSERT INTO TB_VANTAGEM VALUES(2, 'DÉCIMO TERCEIRO', 1100);
INSERT INTO TB_VANTAGEM VALUES(3, 'HORAS EXTRAS', 2.80);
INSERT INTO TB_VANTAGEM VALUES(4, 'LICENÇA MATERNIDADE', 1100);
INSERT INTO TB_VANTAGEM VALUES(5, 'LICENÇA PATERNIDADE', 300);
INSERT INTO TB_VANTAGEM VALUES(6, 'VALE TRANSPORTE', 200);

-- DESCONTO
INSERT INTO TB_DESCONTO VALUES(1, 'INSS', 1100*0.2);
INSERT INTO TB_DESCONTO VALUES(2, 'IMPOSTO DE RENDA', 0.075);
INSERT INTO TB_DESCONTO VALUES(3, 'FALTAS', 89.90);
INSERT INTO TB_DESCONTO VALUES(4, 'ATRASOS', 12.50);

-- PONTO
INSERT INTO TB_PONTO VALUES(1,  SYSDATE,  (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 17));
INSERT INTO TB_PONTO VALUES(2,  SYSDATE,  (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 18));
INSERT INTO TB_PONTO VALUES(3,  SYSDATE,  (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 19));
INSERT INTO TB_PONTO VALUES(4,  SYSDATE,  (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 20));
INSERT INTO TB_PONTO VALUES(5,  SYSDATE,  (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 21));
INSERT INTO TB_PONTO VALUES(6,  SYSDATE,  (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 22));
INSERT INTO TB_PONTO VALUES(7,  SYSDATE,  (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 23));
INSERT INTO TB_PONTO VALUES(8,  SYSDATE,  (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 24));
INSERT INTO TB_PONTO VALUES(9,  SYSDATE,  (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 25));
INSERT INTO TB_PONTO VALUES(10, SYSDATE,  (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 26));
INSERT INTO TB_PONTO VALUES(11, SYSDATE,  (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 27));
INSERT INTO TB_PONTO VALUES(12, SYSDATE,  (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 28));

-- ENTRADA
INSERT INTO TB_ENTRADA VALUES(TO_CHAR(CURRENT_TIMESTAMP, 'HH24:MI:SS'),  (SELECT REF(P) FROM TB_PONTO P WHERE protocolo = 1));
INSERT INTO TB_ENTRADA VALUES(TO_CHAR(CURRENT_TIMESTAMP, 'HH24:MI:SS'),  (SELECT REF(P) FROM TB_PONTO P WHERE protocolo = 2));
INSERT INTO TB_ENTRADA VALUES(TO_CHAR(CURRENT_TIMESTAMP, 'HH24:MI:SS'),  (SELECT REF(P) FROM TB_PONTO P WHERE protocolo = 3));
INSERT INTO TB_ENTRADA VALUES(TO_CHAR(CURRENT_TIMESTAMP, 'HH24:MI:SS'),  (SELECT REF(P) FROM TB_PONTO P WHERE protocolo = 4));
INSERT INTO TB_ENTRADA VALUES(TO_CHAR(CURRENT_TIMESTAMP, 'HH24:MI:SS'),  (SELECT REF(P) FROM TB_PONTO P WHERE protocolo = 5));
INSERT INTO TB_ENTRADA VALUES(TO_CHAR(CURRENT_TIMESTAMP, 'HH24:MI:SS'),  (SELECT REF(P) FROM TB_PONTO P WHERE protocolo = 6));
INSERT INTO TB_ENTRADA VALUES(TO_CHAR(CURRENT_TIMESTAMP, 'HH24:MI:SS'),  (SELECT REF(P) FROM TB_PONTO P WHERE protocolo = 7));
INSERT INTO TB_ENTRADA VALUES(TO_CHAR(CURRENT_TIMESTAMP, 'HH24:MI:SS'),  (SELECT REF(P) FROM TB_PONTO P WHERE protocolo = 8));
INSERT INTO TB_ENTRADA VALUES(TO_CHAR(CURRENT_TIMESTAMP, 'HH24:MI:SS'),  (SELECT REF(P) FROM TB_PONTO P WHERE protocolo = 9));
INSERT INTO TB_ENTRADA VALUES(TO_CHAR(CURRENT_TIMESTAMP, 'HH24:MI:SS'),  (SELECT REF(P) FROM TB_PONTO P WHERE protocolo = 10));
INSERT INTO TB_ENTRADA VALUES(TO_CHAR(CURRENT_TIMESTAMP, 'HH24:MI:SS'),  (SELECT REF(P) FROM TB_PONTO P WHERE protocolo = 11));
INSERT INTO TB_ENTRADA VALUES(TO_CHAR(CURRENT_TIMESTAMP, 'HH24:MI:SS'),  (SELECT REF(P) FROM TB_PONTO P WHERE protocolo = 12));

-- SAIDA
INSERT INTO TB_SAIDA VALUES(TO_CHAR(CURRENT_TIMESTAMP, 'HH24:MI:SS'), (SELECT REF(P) FROM TB_PONTO P WHERE protocolo = 1));
INSERT INTO TB_SAIDA VALUES(TO_CHAR(CURRENT_TIMESTAMP, 'HH24:MI:SS'), (SELECT REF(P) FROM TB_PONTO P WHERE protocolo = 2));
INSERT INTO TB_SAIDA VALUES(TO_CHAR(CURRENT_TIMESTAMP, 'HH24:MI:SS'), (SELECT REF(P) FROM TB_PONTO P WHERE protocolo = 3));
INSERT INTO TB_SAIDA VALUES(TO_CHAR(CURRENT_TIMESTAMP, 'HH24:MI:SS'), (SELECT REF(P) FROM TB_PONTO P WHERE protocolo = 4));
INSERT INTO TB_SAIDA VALUES(TO_CHAR(CURRENT_TIMESTAMP, 'HH24:MI:SS'), (SELECT REF(P) FROM TB_PONTO P WHERE protocolo = 5));
INSERT INTO TB_SAIDA VALUES(TO_CHAR(CURRENT_TIMESTAMP, 'HH24:MI:SS'), (SELECT REF(P) FROM TB_PONTO P WHERE protocolo = 6));
INSERT INTO TB_SAIDA VALUES(TO_CHAR(CURRENT_TIMESTAMP, 'HH24:MI:SS'), (SELECT REF(P) FROM TB_PONTO P WHERE protocolo = 7));
INSERT INTO TB_SAIDA VALUES(TO_CHAR(CURRENT_TIMESTAMP, 'HH24:MI:SS'), (SELECT REF(P) FROM TB_PONTO P WHERE protocolo = 8));
INSERT INTO TB_SAIDA VALUES(TO_CHAR(CURRENT_TIMESTAMP, 'HH24:MI:SS'), (SELECT REF(P) FROM TB_PONTO P WHERE protocolo = 9));
INSERT INTO TB_SAIDA VALUES(TO_CHAR(CURRENT_TIMESTAMP, 'HH24:MI:SS'), (SELECT REF(P) FROM TB_PONTO P WHERE protocolo = 10));
INSERT INTO TB_SAIDA VALUES(TO_CHAR(CURRENT_TIMESTAMP, 'HH24:MI:SS'), (SELECT REF(P) FROM TB_PONTO P WHERE protocolo = 11));
INSERT INTO TB_SAIDA VALUES(TO_CHAR(CURRENT_TIMESTAMP, 'HH24:MI:SS'), (SELECT REF(P) FROM TB_PONTO P WHERE protocolo = 12));

-- PARTICIPACAO
INSERT INTO TB_PARTICIPACAO VALUES((SELECT REF(S) FROM TB_SOCIO S WHERE id_pessoa = 11), (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 1));
INSERT INTO TB_PARTICIPACAO VALUES((SELECT REF(S) FROM TB_SOCIO S WHERE id_pessoa = 12), (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 2));
INSERT INTO TB_PARTICIPACAO VALUES((SELECT REF(S) FROM TB_SOCIO S WHERE id_pessoa = 13), (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 3));
INSERT INTO TB_PARTICIPACAO VALUES((SELECT REF(S) FROM TB_SOCIO S WHERE id_pessoa = 14), (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 4));
INSERT INTO TB_PARTICIPACAO VALUES((SELECT REF(S) FROM TB_SOCIO S WHERE id_pessoa = 15), (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 5));
INSERT INTO TB_PARTICIPACAO VALUES((SELECT REF(S) FROM TB_SOCIO S WHERE id_pessoa = 16), (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 6));

-- BONUS
INSERT INTO TB_BONUS VALUES (10, 0.1,  (SELECT REF(S) FROM TB_SOCIO S WHERE id_pessoa = 11), (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 1));
INSERT INTO TB_BONUS VALUES (12, 0.25, (SELECT REF(S) FROM TB_SOCIO S WHERE id_pessoa = 12), (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 2));
INSERT INTO TB_BONUS VALUES (14, 0.5,  (SELECT REF(S) FROM TB_SOCIO S WHERE id_pessoa = 13), (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 3));
INSERT INTO TB_BONUS VALUES (16, 1,    (SELECT REF(S) FROM TB_SOCIO S WHERE id_pessoa = 14), (SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 4));

-- ACRESCIMO
INSERT INTO TB_ACRESCIMO VALUES((SELECT REF(V) FROM TB_VANTAGEM V WHERE codigo = 1), 
    (SELECT REF(C) FROM TB_CONTRATO C WHERE numero_contrato = 1));
INSERT INTO TB_ACRESCIMO VALUES((SELECT REF(V) FROM TB_VANTAGEM V WHERE codigo = 2), 
    (SELECT REF(C) FROM TB_CONTRATO C WHERE numero_contrato = 1));
INSERT INTO TB_ACRESCIMO VALUES((SELECT REF(V) FROM TB_VANTAGEM V WHERE codigo = 3), 
    (SELECT REF(C) FROM TB_CONTRATO C WHERE numero_contrato = 1));
INSERT INTO TB_ACRESCIMO VALUES((SELECT REF(V) FROM TB_VANTAGEM V WHERE codigo = 6), 
    (SELECT REF(C) FROM TB_CONTRATO C WHERE numero_contrato = 1));
INSERT INTO TB_ACRESCIMO VALUES((SELECT REF(V) FROM TB_VANTAGEM V WHERE codigo = 6), 
    (SELECT REF(C) FROM TB_CONTRATO C WHERE numero_contrato = 4));
INSERT INTO TB_ACRESCIMO VALUES((SELECT REF(V) FROM TB_VANTAGEM V WHERE codigo = 2), 
    (SELECT REF(C) FROM TB_CONTRATO C WHERE numero_contrato = 7));

-- APLICACAO
INSERT INTO TB_APLICACAO VALUES((SELECT REF(V) FROM TB_DESCONTO V WHERE codigo = 1), 
    (SELECT REF(C) FROM TB_CONTRATO C WHERE numero_contrato = 1));
INSERT INTO TB_APLICACAO VALUES((SELECT REF(V) FROM TB_DESCONTO V WHERE codigo = 1), 
    (SELECT REF(C) FROM TB_CONTRATO C WHERE numero_contrato = 2));
INSERT INTO TB_APLICACAO VALUES((SELECT REF(V) FROM TB_DESCONTO V WHERE codigo = 2), 
    (SELECT REF(C) FROM TB_CONTRATO C WHERE numero_contrato = 2));
INSERT INTO TB_APLICACAO VALUES((SELECT REF(V) FROM TB_DESCONTO V WHERE codigo = 2), 
    (SELECT REF(C) FROM TB_CONTRATO C WHERE numero_contrato = 9));

-- PAGAMENTO
INSERT INTO TB_PAGAMENTO VALUES((SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 1),
    (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 17), '12-MAY-2021');
INSERT INTO TB_PAGAMENTO VALUES((SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 1),
    (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 17), '12-JUN-2021');
INSERT INTO TB_PAGAMENTO VALUES((SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 1),
    (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 17), '12-JULY-2021');
INSERT INTO TB_PAGAMENTO VALUES((SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 1),
    (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 18), '12-MAY-2021');
INSERT INTO TB_PAGAMENTO VALUES((SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 1),
    (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 18), '12-JUN-2021');
INSERT INTO TB_PAGAMENTO VALUES((SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 1),
    (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 18), '12-JULY-2021');
INSERT INTO TB_PAGAMENTO VALUES((SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 2),
    (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 19), '20-MAY-2021');
INSERT INTO TB_PAGAMENTO VALUES((SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 2),
    (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 19), '20-JUN-2021');
INSERT INTO TB_PAGAMENTO VALUES((SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 2),
    (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 19), '20-JULY-2021');
INSERT INTO TB_PAGAMENTO VALUES((SELECT REF(E) FROM TB_EMPRESA E WHERE id_pessoa = 2),
    (SELECT REF(F) FROM TB_FUNCIONARIO F WHERE id_pessoa = 20), '20-MAY-2021');

-- NESTED TABLE INSERT
INSERT INTO TB_EMAILS_FUNCIONARIOS VALUES
    (17, TP_NT_EMAIL(TP_EMAIL('email17-1@gmail.com'),TP_EMAIL('email17-2@gmail.com')));

INSERT INTO TB_EMAILS_FUNCIONARIOS VALUES
    (18, TP_NT_EMAIL(TP_EMAIL('email18-1@gmail.com'),TP_EMAIL('email18-2@gmail.com')));

INSERT INTO TB_EMAILS_FUNCIONARIOS VALUES
    (19, TP_NT_EMAIL(TP_EMAIL('email19-2@gmail.com')));

INSERT INTO TB_EMAILS_FUNCIONARIOS VALUES
    (20, TP_NT_EMAIL(TP_EMAIL('email20-1@gmail.com'),TP_EMAIL('email20-2@gmail.com')));

INSERT INTO TB_EMAILS_FUNCIONARIOS VALUES
    (21, TP_NT_EMAIL(TP_EMAIL('email21-1@gmail.com'),TP_EMAIL('email21-2@gmail.com')));

INSERT INTO TB_EMAILS_FUNCIONARIOS VALUES
    (22, TP_NT_EMAIL(TP_EMAIL('email22-1@gmail.com'),TP_EMAIL('email22-2@gmail.com')));

INSERT INTO TB_EMAILS_FUNCIONARIOS VALUES
    (23, TP_NT_EMAIL(TP_EMAIL('email23-1@gmail.com'),TP_EMAIL('email23-2@gmail.com')));

INSERT INTO TB_EMAILS_FUNCIONARIOS VALUES
    (24, TP_NT_EMAIL(TP_EMAIL('email24-1@gmail.com'),TP_EMAIL('email24-2@gmail.com')));

INSERT INTO TB_EMAILS_FUNCIONARIOS VALUES
    (25, TP_NT_EMAIL(TP_EMAIL('email25-1@gmail.com'),TP_EMAIL('email25-2@gmail.com')));

INSERT INTO TB_EMAILS_FUNCIONARIOS VALUES
    (26, TP_NT_EMAIL(TP_EMAIL('email26-1@gmail.com'),TP_EMAIL('email26-2@gmail.com')));

INSERT INTO TB_EMAILS_FUNCIONARIOS VALUES
    (27, TP_NT_EMAIL(TP_EMAIL('email27-1@gmail.com'),TP_EMAIL('email27-2@gmail.com')));

INSERT INTO TB_EMAILS_FUNCIONARIOS VALUES
    (28, TP_NT_EMAIL(TP_EMAIL('email28-1@gmail.com'),TP_EMAIL('email28-2@gmail.com')));

INSERT INTO TB_EMAILS_FUNCIONARIOS VALUES
    (29, TP_NT_EMAIL(TP_EMAIL('email29-1@gmail.com'),TP_EMAIL('email29-2@gmail.com')));

INSERT INTO TB_EMAILS_FUNCIONARIOS VALUES
    (30, TP_NT_EMAIL(TP_EMAIL('email30-1@gmail.com'),TP_EMAIL('email30-2@gmail.com')));

INSERT INTO TB_EMAILS_FUNCIONARIOS VALUES
    (31, TP_NT_EMAIL(TP_EMAIL('email31-1@gmail.com'),TP_EMAIL('email31-2@gmail.com')));

INSERT INTO TB_EMAILS_FUNCIONARIOS VALUES
    (32, TP_NT_EMAIL(TP_EMAIL('email32-1@gmail.com'),TP_EMAIL('email32-2@gmail.com')));

INSERT INTO TB_EMAILS_FUNCIONARIOS VALUES
    (33, TP_NT_EMAIL(TP_EMAIL('email33-1@gmail.com'),TP_EMAIL('email33-2@gmail.com')));

INSERT INTO TB_EMAILS_FUNCIONARIOS VALUES
    (34, TP_NT_EMAIL(TP_EMAIL('email34-1@gmail.com'),TP_EMAIL('email34-2@gmail.com')));

INSERT INTO TB_EMAILS_FUNCIONARIOS VALUES
    (35, TP_NT_EMAIL(TP_EMAIL('email35-1@gmail.com'),TP_EMAIL('email35-2@gmail.com')));

INSERT INTO TB_EMAILS_FUNCIONARIOS VALUES
    (36, TP_NT_EMAIL(TP_EMAIL('email36-1@gmail.com'),TP_EMAIL('email36-2@gmail.com')));

INSERT INTO TB_EMAILS_FUNCIONARIOS VALUES
    (37, TP_NT_EMAIL(TP_EMAIL('email37-1@gmail.com'),TP_EMAIL('email37-2@gmail.com')));

INSERT INTO TB_EMAILS_FUNCIONARIOS VALUES
    (38, TP_NT_EMAIL(TP_EMAIL('email38-1@gmail.com'),TP_EMAIL('email38-2@gmail.com')));

INSERT INTO TB_EMAILS_FUNCIONARIOS VALUES
    (39, TP_NT_EMAIL(TP_EMAIL('email39-1@gmail.com'),TP_EMAIL('email39-2@gmail.com')));

INSERT INTO TB_EMAILS_FUNCIONARIOS VALUES
    (40, TP_NT_EMAIL(TP_EMAIL('email40-1@gmail.com'),TP_EMAIL('email40-2@gmail.com')));

-- VALUE
SELECT VALUE(E).id_pessoa AS ID, VALUE(E).nome_fantasia AS EMPRESA FROM TB_EMPRESA E;
SELECT VALUE(F).id_empresa_func.nome_fantasia AS EMPRESA, VALUE(F).nome AS FUNCIONARIO FROM TB_FUNCIONARIO F;