-- CRIAÇÃO DOS OBJETOS

CREATE OR REPLACE TYPE TP_ENDERECO AS OBJECT(
    cep VARCHAR2(10),
    rua VARCHAR2(100),
    bairro VARCHAR2(100),
    cidade VARCHAR2(100),
    estado CHAR(2)
)NOT FINAL;
/

CREATE OR REPLACE TYPE TP_TELEFONE AS OBJECT(
    numero VARCHAR2(15)
)NOT FINAL;
/

CREATE OR REPLACE TYPE TP_TELEFONES AS VARRAY(5) OF TP_TELEFONE;
/

CREATE OR REPLACE TYPE TP_EMAIL AS OBJECT(
    endereco_email VARCHAR2(50)
)NOT FINAL;
/

CREATE OR REPLACE TYPE TP_EMAILS AS VARRAY(3) OF TP_EMAIL;
/

CREATE OR REPLACE TYPE TP_PESSOA AS OBJECT(
    id_pessoa INTEGER,
    endereco_pessoa TP_ENDERECO,
    numero_pessoa INTEGER,
    telefones_pessoa TP_TELEFONES,
    emails_pessoa TP_EMAILS,

    MEMBER PROCEDURE infoPessoa(SELF TP_PESSOA)
)NOT FINAL;
/

CREATE OR REPLACE TYPE BODY TP_PESSOA AS
    MEMBER PROCEDURE infoPessoa (SELF TP_PESSOA) IS
        BEGIN
            DBMS_OUTPUT.PUT_LINE('INFORMAÇÕES da PESSOA');
            DBMS_OUTPUT.PUT_LINE('ID PESSOA: ' || id_pessoa);
            DBMS_OUTPUT.PUT_LINE('ENDERECO: ' || endereco_pessoa);
        END;
END;
/

-- =-=-= Especializações de Pessoa =-=-=
CREATE OR REPLACE TYPE TP_EMPRESA UNDER TP_PESSOA(
    cnpj VARCHAR2(20), 
    razao_social VARCHAR2(50),
    nome_fantasia VARCHAR2(50)
)NOT FINAL;
/

CREATE OR REPLACE TYPE TP_PESSOA_FISICA UNDER TP_PESSOA(
    cpf VARCHAR2(15),
    nome VARCHAR2(100),
    data_de_nascimento DATE,

    OVERRIDING MEMBER PROCEDURE infoPessoa(SELF TP_PESSOA_FISICA)
)NOT FINAL;
/

CREATE OR REPLACE TYPE BODY TP_PESSOA_FISICA AS
    OVERRIDING MEMBER PROCEDURE infoPessoa (SELF TP_PESSOA_FISICA) IS
        BEGIN
            DBMS_OUTPUT.PUT_LINE('INFORMAÇÕES da PESSOA');
            DBMS_OUTPUT.PUT_LINE('ID PESSOA: ' || id_pessoa);
            DBMS_OUTPUT.PUT_LINE('ENDERECO: ' || endereco_pessoa);
            DBMS_OUTPUT.PUT_LINE('NOME: ' || nome);
            DBMS_OUTPUT.PUT_LINE('CPF: ' || cpf);
            DBMS_OUTPUT.PUT_LINE('DATA DE NASCIMENTO: ' || TO_CHAR(data_de_nascimento));
        END;
END;
/

-- =-=-= Fim Especializações Pessoa =-=-=
CREATE OR REPLACE TYPE TP_SOCIO UNDER TP_PESSOA_FISICA(
    numero_registro INTEGER,
    data_afiliacao DATE,
    valor_investimento NUMBER(10,2), 
    porcentagem_nos_lucros FLOAT(2)
)NOT FINAL;
/

CREATE OR REPLACE TYPE TP_DEPARTAMENTO AS OBJECT(
    numero INTEGER,
    empresa_dep REF TP_EMPRESA, 
    nome VARCHAR2(80),
    data_criacao DATE,
    situacao CHAR(1),

    MAP MEMBER FUNCTION nomeDepartamento RETURN VARCHAR2

)NOT FINAL;
/

CREATE OR REPLACE TYPE BODY TP_DEPARTAMENTO AS
    MAP MEMBER FUNCTION nomeDepartamento RETURN VARCHAR2 IS
        d VARCHAR2(80) := nome;
    BEGIN
        RETURN d
    END;
END;
/

CREATE OR REPLACE TYPE TP_CONTRATO AS OBJECT(
    numero_contrato INTEGER,
    tipo_contrato VARCHAR2(80),
    data_admissao DATE, 
    cargo VARCHAR2(50), 
    salario_bruto_mensal NUMBER(10,2),
    jornada_trabalho_semanal INTEGER
)NOT FINAL;
/

CREATE OR REPLACE TYPE TP_FUNCIONARIO UNDER TP_PESSOA_FISICA(
    ctps VARCHAR2(15),
    numero_departamento REF TP_DEPARTAMENTO,  
    numero_contrato_func REF TP_CONTRATO, 
    id_empresa_func REF TP_EMPRESA
)NOT FINAL;
/

CREATE OR REPLACE TYPE BODY TP_FUNCIONARIO AS
    MEMBER FUNCTION salarioBrutoAnual RETURN NUMBER IS
    BEGIN
        RETURN numero_contrato_func.salario_bruto_mensal * 12
    END;
END;
/

CREATE OR REPLACE TYPE TP_GERENTE UNDER TP_FUNCIONARIO(
);
/

ALTER TYPE TP_FUNCIONARIO ADD ATTRIBUTE (gerente_func REF TP_GERENTE) CASCADE;

CREATE OR REPLACE TYPE TP_CONTA_BANCARIA AS OBJECT(
    agencia INTEGER, 
    numero_conta INTEGER,
    numero_banco INTEGER, 
    id_titular REF TP_PESSOA 
)NOT FINAL;
/

CREATE OR REPLACE TYPE TP_VANTAGEM AS OBJECT(
    codigo INTEGER, 
    descricao VARCHAR2(50),
    valor NUMBER(10,2) 
)NOT FINAL;
/

CREATE OR REPLACE TYPE TP_DESCONTO AS OBJECT(
    codigo INTEGER, 
    descricao VARCHAR2(50),
    valor NUMBER(10,2) 
)NOT FINAL;
/

CREATE OR REPLACE TYPE TP_PONTO AS OBJECT(
    protocolo INTEGER,
    data_atual DATE, 
    ponto_funcionario REF TP_FUNCIONARIO 
)NOT FINAL;
/

CREATE OR REPLACE TYPE TP_ENTRADA AS OBJECT(
    hora_entrada VARCHAR2(12), 
    protocolo_ponto REF TP_PONTO 
)NOT FINAL;
/

CREATE OR REPLACE TYPE TP_SAIDA AS OBJECT(
    hora_saida VARCHAR2(12), 
    protocolo_ponto REF TP_PONTO 
)NOT FINAL;
/

CREATE OR REPLACE TYPE TP_PARTICIPACAO AS OBJECT(
    part_socio REF TP_SOCIO, 
    part_empresa REF TP_EMPRESA 
)NOT FINAL;
/

CREATE OR REPLACE TYPE TP_BONUS AS OBJECT(
    identificador INTEGER, 
    porcentagem_bonus FLOAT(2), 
    socio_empresa REF PARTICIPACAO 
)NOT FINAL;
/

CREATE OR REPLACE TYPE TP_ACRESCIMO AS OBJECT(
    codigo_vantagem REF TP_VANTAGEM, 
    num_contrato REF TP_CONTRATO
)NOT FINAL NOT INSTANTIABLE;
/

CREATE OR REPLACE TYPE TP_APLICACAO AS OBJECT(
    codigo_vantagem REF TP_DESCONTO, 
    num_contrato REF TP_CONTRATO
)NOT FINAL NOT INSTANTIABLE;
/

CREATE OR REPLACE TYPE TP_PAGAMENTO AS OBJECT(
    pag_empresa REF TP_EMPRESA, 
    pag_funcionario REF TP_FUNCIONARIO,
    pag_data DATE
)NOT FINAL;
/
-- FIM CRIAÇÃO OBJETOS

-- TABELAS
CREATE TABLE TB_EMPRESA OF TP_EMPRESA(
    cnpj UNIQUE,
    id_pessoa PRIMARY KEY 
);
/

CREATE TABLE TB_SOCIO OF TP_SOCIO(
    id_pessoa PRIMARY KEY 
);
/

CREATE TABLE TB_DEPARTAMENTO OF TP_DEPARTAMENTO(
    numero PRIMARY KEY
);
/

CREATE TABLE TB_CONTRATO OF TP_CONTRATO(
    numero_contrato PRIMARY KEY,

    CHECK(salario_bruto_mensal >= 1100),
    CHECK(jornada_trabalho_semanal <= 44)
);
/

CREATE TABLE TB_FUNCIONARIO OF TP_FUNCIONARIO(
    id_pessoa PRIMARY KEY,
    ctps UNIQUE
);
/

CREATE TABLE TB_CONTA_BANCARIA OF TP_CONTA_BANCARIA(
    numero_conta PRIMARY KEY
);
/

CREATE TABLE TB_VANTAGEM OF TP_VANTAGEM(
    codigo PRIMARY KEY
);
/

CREATE TABLE TB_DESCONTO OF TP_DESCONTO(
    codigo PRIMARY KEY
);
/

CREATE TABLE TB_PONTO OF TP_PONTO(
    protocolo PRIMARY KEY 
);
/

CREATE TABLE TB_ENTRADA OF TP_ENTRADA;
/

CREATE TABLE TB_SAIDA OF TP_SAIDA;
/

CREATE TABLE TB_PARTICIPACAO OF TP_PARTICIPACAO;
/

CREATE TABLE TB_BONUS OF TP_BONUS(
    identificador PRIMARY KEY
);
/

CREATE TABLE TB_ACRESCIMO OF TP_ACRESCIMO;
/

CREATE TABLE TB_APLICACAO OF TP_APLICACAO;
/

CREATE TABLE TB_PAGAMENTO OF TP_PAGAMENTO;
/